apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: LoadBalancer
  creationTimestamp: null
  labels:
    io.kompose.service: combine
  name: combine
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: combine
  type: LoadBalancer
status:
  loadBalancer: {}
